services:
  app:
    build:
      context: .  # Контекст сборки (корень проекта)
      dockerfile: Docker/Dockerfile  # Путь к Dockerfile в папке Docker
    container_name: car-price-predictor
    ports:
      - "8000:8000"  # Порт для FastAPI
      - "8501:8501"  # Порт для Streamlit
    volumes:
      - .:/app  # Монтируем текущую папку в контейнер
    restart: unless-stopped  # Перезапуск контейнера при его сбое