services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    container_name: car-price-predictor
    ports:
      - "8000:8000" 
      - "8501:8501" 
    volumes:
      - .:/app 
    restart: unless-stopped  