package_name: car_price_predictor
pipeline_name: car_price_pipeline
pipeline_save_file: car_price_pipeline_output

dataset_file: data/cars.csv  

target: Price

features:
  - Manufacturer
  - Model
  - Category
  - Leather_interior
  - Fuel_type
  - Engine_volume
  - Mileage
  - Cylinders
  - Gear_box_type
  - Drive_wheels
  - Doors
  - Wheel
  - Color
  - Airbags
  - Age
  - Levy_rate

variables_to_drop:
  - ID
  - Levy
  - Prod. year

categorical_vars:
  - Manufacturer
  - Model
  - Category
  - Fuel_type
  - Gear_box_type
  - Drive_wheels
  - Wheel
  - Color

numerical_vars:
  - Engine_volume
  - Mileage
  - Cylinders
  - Airbags
  - Age
  - Levy_rate

categorical_vars_with_na:
  - Category
  - Fuel_type
  - Gear_box_type
  - Color

numerical_vars_with_na:
  - Mileage
  - Engine_volume

test_size: 0.2

random_state: 42

n_trials: 15
